import React, { useState, useCallback, useEffect, useRef } from 'react';
import './App.css';
import Sidebar from './components/Sidebar';
import CanvasArea from './components/CanvasArea';
import Timeline from './components/Timeline';
import KeyboardShortcutsOverlay from './components/KeyboardShortcutsOverlay';
import StatusBar from './components/StatusBar';
import ExportModal from './components/ExportModal';
import { flipFrameH, flipFrameV } from './utils/drawingTools';
import { exportFramePNG, exportSpritesheet, exportAllFrames, exportJSON } from './utils/exportUtils';
import { useAutoSave } from './hooks/useAutoSave';